server:
  port: 8085

spring:
  debug: true
  application:
    name: user-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/user_db
    username: user_user
    password: user_pw
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  data:
    redis:
      host: localhost
      port: 16379

  jpa:
    hibernate:
      ddl-auto: none

# (??) ?? ?? ??? ? ?? prefix? ?? ????
app:
  cache:
    user:
      ttl-seconds: 300
      key-prefix: user:detail

# JWT ?? ??? ?? ? ? ?? ??
security:
  jwt:
    secret: ${JWT_SECRET:local-dev-secret-change-me}  # (??? ??? ?? ???? ??)

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
