services:
  postgres:
    image: postgres:16
    container_name: msashop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - msashop_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro

  redis:
    image: redis:7
    container_name: msashop-redis
    ports:
      - "16379:6379"

volumes:
  msashop_pgdata:
